// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.condominio.domain;

import com.condominio.domain.CategoriaDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CategoriaDataOnDemand_Roo_Configurable {
    
    declare @type: CategoriaDataOnDemand: @Configurable;
    
}
