// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.condominio.domain;

import com.condominio.domain.Categoria;
import com.condominio.domain.CategoriaDataOnDemand;
import com.condominio.repository.CategoriaRepository;
import com.condominio.service.CategoriaService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CategoriaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CategoriaDataOnDemand: @Component;
    
    private Random CategoriaDataOnDemand.rnd = new SecureRandom();
    
    private List<Categoria> CategoriaDataOnDemand.data;
    
    @Autowired
    CategoriaService CategoriaDataOnDemand.categoriaService;
    
    @Autowired
    CategoriaRepository CategoriaDataOnDemand.categoriaRepository;
    
    public Categoria CategoriaDataOnDemand.getNewTransientCategoria(int index) {
        Categoria obj = new Categoria();
        setDescricao(obj, index);
        setNome(obj, index);
        return obj;
    }
    
    public void CategoriaDataOnDemand.setDescricao(Categoria obj, int index) {
        String descricao = "descricao_" + index;
        if (descricao.length() > 1000) {
            descricao = descricao.substring(0, 1000);
        }
        obj.setDescricao(descricao);
    }
    
    public void CategoriaDataOnDemand.setNome(Categoria obj, int index) {
        String nome = "nome_" + index;
        if (nome.length() > 40) {
            nome = nome.substring(0, 40);
        }
        obj.setNome(nome);
    }
    
    public Categoria CategoriaDataOnDemand.getSpecificCategoria(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Categoria obj = data.get(index);
        Long id = obj.getId();
        return categoriaService.findCategoria(id);
    }
    
    public Categoria CategoriaDataOnDemand.getRandomCategoria() {
        init();
        Categoria obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return categoriaService.findCategoria(id);
    }
    
    public boolean CategoriaDataOnDemand.modifyCategoria(Categoria obj) {
        return false;
    }
    
    public void CategoriaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = categoriaService.findCategoriaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Categoria' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Categoria>();
        for (int i = 0; i < 10; i++) {
            Categoria obj = getNewTransientCategoria(i);
            try {
                categoriaService.saveCategoria(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            categoriaRepository.flush();
            data.add(obj);
        }
    }
    
}
