// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.condominio.domain;

import com.condominio.domain.MoradorDataOnDemand;
import com.condominio.domain.MoradorIntegrationTest;
import com.condominio.repository.MoradorRepository;
import com.condominio.service.MoradorService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MoradorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MoradorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MoradorIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MoradorIntegrationTest: @Transactional;
    
    @Autowired
    MoradorDataOnDemand MoradorIntegrationTest.dod;
    
    @Autowired
    MoradorService MoradorIntegrationTest.moradorService;
    
    @Autowired
    MoradorRepository MoradorIntegrationTest.moradorRepository;
    
    @Test
    public void MoradorIntegrationTest.testCountAllMoradors() {
        Assert.assertNotNull("Data on demand for 'Morador' failed to initialize correctly", dod.getRandomMorador());
        long count = moradorService.countAllMoradors();
        Assert.assertTrue("Counter for 'Morador' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MoradorIntegrationTest.testFindMorador() {
        Morador obj = dod.getRandomMorador();
        Assert.assertNotNull("Data on demand for 'Morador' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Morador' failed to provide an identifier", id);
        obj = moradorService.findMorador(id);
        Assert.assertNotNull("Find method for 'Morador' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Morador' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MoradorIntegrationTest.testFindAllMoradors() {
        Assert.assertNotNull("Data on demand for 'Morador' failed to initialize correctly", dod.getRandomMorador());
        long count = moradorService.countAllMoradors();
        Assert.assertTrue("Too expensive to perform a find all test for 'Morador', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Morador> result = moradorService.findAllMoradors();
        Assert.assertNotNull("Find all method for 'Morador' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Morador' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MoradorIntegrationTest.testFindMoradorEntries() {
        Assert.assertNotNull("Data on demand for 'Morador' failed to initialize correctly", dod.getRandomMorador());
        long count = moradorService.countAllMoradors();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Morador> result = moradorService.findMoradorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Morador' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Morador' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MoradorIntegrationTest.testFlush() {
        Morador obj = dod.getRandomMorador();
        Assert.assertNotNull("Data on demand for 'Morador' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Morador' failed to provide an identifier", id);
        obj = moradorService.findMorador(id);
        Assert.assertNotNull("Find method for 'Morador' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMorador(obj);
        Integer currentVersion = obj.getVersion();
        moradorRepository.flush();
        Assert.assertTrue("Version for 'Morador' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MoradorIntegrationTest.testUpdateMoradorUpdate() {
        Morador obj = dod.getRandomMorador();
        Assert.assertNotNull("Data on demand for 'Morador' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Morador' failed to provide an identifier", id);
        obj = moradorService.findMorador(id);
        boolean modified =  dod.modifyMorador(obj);
        Integer currentVersion = obj.getVersion();
        Morador merged = moradorService.updateMorador(obj);
        moradorRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Morador' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MoradorIntegrationTest.testSaveMorador() {
        Assert.assertNotNull("Data on demand for 'Morador' failed to initialize correctly", dod.getRandomMorador());
        Morador obj = dod.getNewTransientMorador(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Morador' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Morador' identifier to be null", obj.getId());
        moradorService.saveMorador(obj);
        moradorRepository.flush();
        Assert.assertNotNull("Expected 'Morador' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MoradorIntegrationTest.testDeleteMorador() {
        Morador obj = dod.getRandomMorador();
        Assert.assertNotNull("Data on demand for 'Morador' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Morador' failed to provide an identifier", id);
        obj = moradorService.findMorador(id);
        moradorService.deleteMorador(obj);
        moradorRepository.flush();
        Assert.assertNull("Failed to remove 'Morador' with identifier '" + id + "'", moradorService.findMorador(id));
    }
    
}
