// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.condominio.domain;

import com.condominio.domain.ReclamacaoDataOnDemand;
import com.condominio.domain.ReclamacaoIntegrationTest;
import com.condominio.repository.ReclamacaoRepository;
import com.condominio.service.ReclamacaoService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ReclamacaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ReclamacaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ReclamacaoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ReclamacaoIntegrationTest: @Transactional;
    
    @Autowired
    ReclamacaoDataOnDemand ReclamacaoIntegrationTest.dod;
    
    @Autowired
    ReclamacaoService ReclamacaoIntegrationTest.reclamacaoService;
    
    @Autowired
    ReclamacaoRepository ReclamacaoIntegrationTest.reclamacaoRepository;
    
    @Test
    public void ReclamacaoIntegrationTest.testCountAllReclamacaos() {
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to initialize correctly", dod.getRandomReclamacao());
        long count = reclamacaoService.countAllReclamacaos();
        Assert.assertTrue("Counter for 'Reclamacao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ReclamacaoIntegrationTest.testFindReclamacao() {
        Reclamacao obj = dod.getRandomReclamacao();
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to provide an identifier", id);
        obj = reclamacaoService.findReclamacao(id);
        Assert.assertNotNull("Find method for 'Reclamacao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Reclamacao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ReclamacaoIntegrationTest.testFindAllReclamacaos() {
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to initialize correctly", dod.getRandomReclamacao());
        long count = reclamacaoService.countAllReclamacaos();
        Assert.assertTrue("Too expensive to perform a find all test for 'Reclamacao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Reclamacao> result = reclamacaoService.findAllReclamacaos();
        Assert.assertNotNull("Find all method for 'Reclamacao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Reclamacao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ReclamacaoIntegrationTest.testFindReclamacaoEntries() {
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to initialize correctly", dod.getRandomReclamacao());
        long count = reclamacaoService.countAllReclamacaos();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Reclamacao> result = reclamacaoService.findReclamacaoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Reclamacao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Reclamacao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ReclamacaoIntegrationTest.testFlush() {
        Reclamacao obj = dod.getRandomReclamacao();
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to provide an identifier", id);
        obj = reclamacaoService.findReclamacao(id);
        Assert.assertNotNull("Find method for 'Reclamacao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyReclamacao(obj);
        Integer currentVersion = obj.getVersion();
        reclamacaoRepository.flush();
        Assert.assertTrue("Version for 'Reclamacao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReclamacaoIntegrationTest.testUpdateReclamacaoUpdate() {
        Reclamacao obj = dod.getRandomReclamacao();
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to provide an identifier", id);
        obj = reclamacaoService.findReclamacao(id);
        boolean modified =  dod.modifyReclamacao(obj);
        Integer currentVersion = obj.getVersion();
        Reclamacao merged = reclamacaoService.updateReclamacao(obj);
        reclamacaoRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Reclamacao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReclamacaoIntegrationTest.testSaveReclamacao() {
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to initialize correctly", dod.getRandomReclamacao());
        Reclamacao obj = dod.getNewTransientReclamacao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Reclamacao' identifier to be null", obj.getId());
        reclamacaoService.saveReclamacao(obj);
        reclamacaoRepository.flush();
        Assert.assertNotNull("Expected 'Reclamacao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ReclamacaoIntegrationTest.testDeleteReclamacao() {
        Reclamacao obj = dod.getRandomReclamacao();
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Reclamacao' failed to provide an identifier", id);
        obj = reclamacaoService.findReclamacao(id);
        reclamacaoService.deleteReclamacao(obj);
        reclamacaoRepository.flush();
        Assert.assertNull("Failed to remove 'Reclamacao' with identifier '" + id + "'", reclamacaoService.findReclamacao(id));
    }
    
}
