// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.condominio.domain;

import com.condominio.domain.ReclamacaoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ReclamacaoIntegrationTest_Roo_Configurable {
    
    declare @type: ReclamacaoIntegrationTest: @Configurable;
    
}
